version: "3.9"

services:
  telegram-reposter-bot:
    container_name: telegram-reposter-bot
    working_dir: /aplhagroup_reposter
    ports:
      - "5431:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file:
      - .env
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python3 main.py"